### ISSUE TITLE
Only 1 motor runs when sending both motors the same speed

### ISSUE THREAD

**Issue by yurigorokhov** [Makeblock-official/PythonForMegaPi#1]
I have a weird issue where I try to send both motors the same speed value, only one motor responds:

```
megaPi.MotorRun(1, 0)
megaPi.MotorRun(2, 0)
time.Sleep(1 * time.Second)
megaPi.MotorRun(1, 50)
megaPi.MotorRun(2, 50)
time.Sleep(5 * time.Second)
megaPi.MotorRun(1, 0)
megaPi.MotorRun(2, 0)
```

However, when the two values are slightly different, then both motors respond correctly:

```
megaPi.MotorRun(1, 0)
megaPi.MotorRun(2, -1)
time.Sleep(1 * time.Second)
megaPi.MotorRun(1, 50)
megaPi.MotorRun(2, -50)
time.Sleep(5 * time.Second)
megaPi.MotorRun(1, 0)
megaPi.MotorRun(2, -1)
```

I am using a USB connection to the raspberry pi and talking using serial over `/dev/ttyUSB0`.

Is this expected?

**Comment by YanMinge** [comment]
This is a firmware driver issue， and  we have fixed it. please update your megapi firmware from [https://github.com/Makeblock-official/Makeblock-Libraries](https://github.com/Makeblock-official/Makeblock-Libraries)
