### ISSUE TITLE
temperatureRead function misses 'slot' parameter

### ISSUE THREAD

**Issue by rdhelli** [Makeblock-official/PythonForMegaPi#15]
`Firmware_for_MegaPi.ino` expects to read slot from Buffer(7), see pull request: https://github.com/Makeblock-official/PythonForMegaPi/pull/14

**Comment by rdhelli** [comment]
sorry, why was this issue closed? the temperature function still needs to send the connected slot value to megapi. I have already made a [pull request](https://github.com/Makeblock-official/PythonForMegaPi/pull/14/commits/5629f7ea40b3d6d7b6095300bef156dcb89ae50b) about it.

**Comment by MrHezhisheng** [comment]
Thank you, I will update the next version.
