### ISSUE TITLE
The Raspberry Pi Configuration window has changed.

### ISSUE THREAD

**Issue by clplaneguy** [Makeblock-official/PythonForMegaPi#17]
Please update!  The new window has more options.  In particular, there are two options for serial communication.  One for serial console and another for serial port.  This is very important to me, I need to know which to chose.  I would say close the console and open the port.  But I really do not know because I can not get it to work.  I have read a weeks worth of documents but can not find the combination of commands required to get the RaspberryPi3 to successfully communicate with the MegaPi2560 .

The current versions of the software seem to be . . .  
MegaPi2560 firmware                     | 0e.01.016
Arduino IDE                                     | 1.8.8
MegaPi library for the Arduino IDE  | 3.2.6
Python library for the Raspberry      | 0.1.9

PS.  I would appreciate your input in the forum.

![croped](https://user-images.githubusercontent.com/23004042/51089305-ad027800-1730-11e9-9351-7543cad11bef.png)

Updated 1/13/2019
Photo updated to be the correct choice.

**Comment by WrickColl** [comment]
You need to enable the port, but disable the console

**Comment by clplaneguy** [comment]
I have another communication example from the Internet working through the
USB port.
http://www.doctormonk.com/2012/04/raspberry-pi-and-arduino.html
The one difference that I can see, that may be the cause of the problem, is
that the example explicitly sets the baud rate at 9600!  I use 115200!  I
will use this concept with the python-for-megapi process.
http://learn.makeblock.com/python-for-megapi/

**Comment by clplaneguy** [comment]
Seems correct.  I will now, and forever more, use this as my default.
However, somehow, that is not enough.  From the Internet communication
example

http://www.doctormonk.com/2012/04/raspberry-pi-and-arduino.html

I get

pi@raspberrypi:~ $ ls

2019-01-10-102843_1824x984_scrot.png  BotBlink.py Documents exploringRPi
  image.jpg MotorRun.py MyPythonLib.py  nano.save.1 oldconffiles Public
Quick-Start Guide ex 2.py  Quick-Start Guide.py test

2019-01-10-102921_1824x984_scrot.png  Desktop Downloads FirstProgram.py
 MakeblockTest.py Music nano.save      nano.save.2 Pictures python_games
Quick-Start Guide ex 3.py  Templates Videos

pi@raspberrypi:~ $ ls /dev/tty*

/dev/tty    /dev/tty11 /dev/tty15  /dev/tty19 /dev/tty22 /dev/tty26
 /dev/tty3 /dev/tty33 /dev/tty37 /dev/tty40  /dev/tty44 /dev/tty48
/dev/tty51 /dev/tty55 /dev/tty59  /dev/tty62 /dev/tty9

/dev/tty0   /dev/tty12 /dev/tty16  /dev/tty2 /dev/tty23 /dev/tty27
 /dev/tty30 /dev/tty34 /dev/tty38 /dev/tty41  /dev/tty45 /dev/tty49
/dev/tty52 /dev/tty56 /dev/tty6   /dev/tty63 /dev/ttyAMA0

/dev/tty1   /dev/tty13 /dev/tty17  /dev/tty20 /dev/tty24 /dev/tty28
 /dev/tty31 /dev/tty35 /dev/tty39 /dev/tty42  /dev/tty46 /dev/tty5
/dev/tty53 /dev/tty57 /dev/tty60  /dev/tty7 /dev/ttyprintk

/dev/tty10  /dev/tty14 /dev/tty18  /dev/tty21 /dev/tty25 /dev/tty29
 /dev/tty32 /dev/tty36 /dev/tty4 /dev/tty43  /dev/tty47 /dev/tty50
/dev/tty54 /dev/tty58 /dev/tty61  /dev/tty8 /dev/ttyS0

pi@raspberrypi:~ $ python

Python 2.7.13 (default, Sep 26 2018, 18:42:22)

[GCC 6.3.0 20170516] on linux2

Type "help", "copyright", "credits" or "license" for more information.

>>> import serial

>>> ser = serial.Serial('/dev/ttyAMA0', 115200)

>>> while 1 :

...     ser.readline()

...

^CTraceback (most recent call last):

 File "<stdin>", line 2, in <module>

 File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line
461, in read

   ready,_,_ = select.select([self.fd],[],[], self._timeout)

KeyboardInterrupt

>>> ser.write('5')

1

>>> import serial

>>> ser = serial.Serial('/dev/ttyS0', 115200)

Traceback (most recent call last):

 File "<stdin>", line 1, in <module>

 File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line
282, in __init__

   self.open()

 File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line
296, in open

   self._reconfigurePort()

 File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line
325, in _reconfigurePort

   raise SerialException("Could not configure port: %s" % msg)

serial.serialutil.SerialException: Could not configure port: (5,
'Input/output error')

>>> ser = serial.Serial('/dev/ttyAMA0', 115200)

>>> ser = serial.Serial('/dev/ttyS0', 115200)

Traceback (most recent call last):

 File "<stdin>", line 1, in <module>

 File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line
282, in __init__

   self.open()

 File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line
296, in open

   self._reconfigurePort()

 File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line
325, in _reconfigurePort

   raise SerialException("Could not configure port: %s" % msg)

serial.serialutil.SerialException: Could not configure port: (5,
'Input/output error')

>>>

So, in summery, UART1(*/dev/ttyS0*) does not pass the first test and UART0(
*/dev/ttyAMA0*) does not pass the second test.

I am not concerned about and do not intend to use Bluetooth at this time.
Thus, I would prefer to use the better of the two UARTs( PL011, UART0,
*/dev/ttyAMA0*).  On the Raspberry Pi 3, I should open the port, close the
console, use a baud rate of 115200!  The MegaPi has two serial ports.  One
is the standard USB A-B cable(printer cable)(B-side) port and the other is
the hidden (TX2/TXD2, RX2/RXD2)port.  Are these two different ports or in
fact the same port?
The MegaPi should have a (RX1/RXD1, TX1/TXD1) port and a (RX2/RXD2,
TX2/TXD2) port.  If it does actually have two different ports, then I do
not know how to distinguish between them.

I have gotten the Raspberry Pi to communicate with the MegaPi.  It is easy,
with the USB A-B cable.  But, I have never gotten communication without the
cable.  The little 2x5 16cm connector is in soldered in place.  They seem
to be all hot joints (no cold welds).  I can see no shorts in the solder
joints.  The spacing between the two boards seems to be correct (19cm).
Meaning that the 2x5 connector seems to be fully plugged into the Raspberry
Pi.

If someone has a new idea as to why the cable is required *PLEASE* send me
a note!

I will now find and use my meter to check the voltages and recheck the
Raspberry Pi settings.

THANK YOU

**Comment by clplaneguy** [comment]
THANK YOU

I finally got it to work.  To reach the finish line on this it is a chain of events.  If any one link in the chain is not correct then the whole process fails.  In short, the steps I would make note of is as follows . . .
1) From configure turn off serial console.  Turn on serial port.
2) Activate UART1(PL011, **/dev/ttyAMA0**) on the GPIO.  (many details)
3) Turn on the motor power to use the motors.
4) Do not use idle.  Use a terminal.
5) Use python 2 not python 3.
