### ISSUE TITLE
Compile Firmware_for_MegaPiPro.ino Failed

### ISSUE THREAD

**Issue by kingrocky617** [Makeblock-official/PythonForMegaPi#3]
1. Open Audrino IDE
2. Open Firmware_for_MegaPiPro.ino file.
3. Compile and Upload this file.
4. Then came out the error:
'Serial3' was not declared in this scope

I need to remove the Serial3 and Serial2 code, then I could compile and upload sucessed.

Why?

**Comment by Makeblock-official** [comment]
I think you select the wrong type of board.
