### ISSUE TITLE
lcdDisplay Function missing in MegaPi class

### ISSUE THREAD

**Issue by oliviercathala** [Makeblock-official/PythonForMegaPi#7]
Hello,

I can’t find lcdDisplay method in MegePi whereas it is documented in readme (display section). 

How can we use the Me LCD display with Python on megapi?

Thanks,

Olivier

**Comment by YanMinge** [comment]
I see it after I release the new version. But LCD interface didn't support now.

**Comment by oliviercathala** [comment]
Thank you for your quick answer. I hope LCD screen will be supported soon ;-)
